import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <header className="p-10 mx-20 sticky top-0">
            <Navbar/>
          </header>
          <main>
            {children}
          </main>
          <footer className="text-center bottom-0">CopyRight&copy;</footer>
        </div>
      </body>
    </html >
  );
}
